import { UserProfile, HireRequest, ServiceReview, HireAdminSettings } from '../types';

export const DEFAULT_HIRE_ADMIN_SETTINGS: HireAdminSettings = {
  minServiceBudget: 200,
  maxServiceBudget: 50000,
  defaultSearchRadiusKm: 15,
  requireVerificationForWork: true,
  requestExpirationHours: 24,
  cancellationWindowHours: 2,
  // Automated Service Fee / Commission Settings (Step 4)
  serviceFeeEnabled: true,
  commissionPercentage: 5,
  fixedServiceFee: 10,
  minServiceFee: 10,
  maxServiceFee: 500,
  feeEffectiveDate: '2026-01-01',
};

export const SAMPLE_SEED_WORKERS: UserProfile[] = [
  {
    userId: 'worker-01-shafiq',
    fullName: 'মো: শফিকুল ইসলাম',
    bio: '১০ বছরের অভিজ্ঞ মাস্টার ইলেকট্রিশিয়ান ও সার্কিট ডিজাইনার। যেকোনো ধরনের জটিল ওয়্যারিং, ফ্যান, লাইট, সার্কিট ব্রেকার ও সাব-স্টেশন সংযোগে দক্ষ।',
    phoneNumber: '০১৭০১-১২২৩৩৩',
    email: 'shafiq.tech@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker', 'customer'],
    capabilities: ['worker', 'customer'],
    professions: ['ইলেকট্রিশিয়ান (Electrician)', 'আইপিএস ও সোলার টেকনিশিয়ান'],
    mainProfession: 'ইলেকট্রিশিয়ান (Electrician)',
    skills: [
      'Fan Installation (ফ্যান ফিটিং)',
      'House Wiring (হাউস ওয়্যারিং)',
      'MCB Installation (সার্কিট ব্রেকার)',
      'Switch Repair (সুইচবোর্ড মেরামত)',
      'Generator Servicing (জেনারেটর সার্ভিসিং)',
    ],
    experiences: [
      {
        profession: 'ইলেকট্রিশিয়ান (Electrician)',
        years: 10,
        description: 'আবাসিক ও বাণিজ্যিক কমপ্লেক্সের পূর্ণাঙ্গ ইলেকট্রিক ওয়্যারিং সমাধান।',
        isMain: true,
      },
    ],
    workHistories: [
      {
        id: 'wh-s1',
        company: 'পাওয়ারটেক বিডি লিমিটেড',
        position: 'চিফ ইলেকট্রিশিয়ান',
        startDate: '২০১৮',
        endDate: 'চলমান',
        currentlyWorking: true,
        location: 'মিরপুর, ঢাকা',
        jobDetails: 'অ্যাপার্টমেন্ট প্রজেক্ট ও কমার্শিয়াল ভবনে বিদ্যুৎ সংযোগ স্থাপন।',
      },
    ],
    serviceAreas: ['মিরপুর-১০', 'মিরপুর-২', 'পল্লবী', 'কাজীপাড়া', 'শেওড়াপাড়া', 'উত্তরা'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      unionWard: 'ওয়ার্ড ৩',
      areaRoad: 'রোড ২, ব্লক সি',
      fullAddress: 'মিরপুর ১০, ঢাকা',
    },
    currentLocation: {
      latitude: 23.8071,
      longitude: 90.3686,
      accuracyMeters: 10,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'মিরপুর ১০ গোলচত্বর, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.9,
    reviewCount: 38,
    completedJobsCount: 84,
    joinedDate: '২০২২',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 100,
    isProfileSetupComplete: true,
    serviceCategoryModes: ['physical'],
    searchKeywords: [
      'Electrician', 'ইলেকট্রিশিয়ান', 'ইলেকট্রিশিয়ান', 'ইলেকট্রিক মিস্ত্রি',
      'বৈদ্যুতিক', 'ওয়্যারিং', 'হাউস ওয়্যারিং', 'ফ্যান ফিটিং', 'সোলার প্যানেল টেকনিশিয়ান', 'Solar Panel'
    ],
    pricing: {
      visitFee: 300,
      dailyRate: 1200,
      isNegotiable: true,
      rateDescription: 'ভিজিট ফি ৩০০ টাকা + কাজের পরিধি অনুযায়ী চুক্তি'
    },
  },
  {
    userId: 'worker-02-tarik',
    fullName: 'তারেক মাহমুদ',
    bio: 'সার্টিফাইড এয়ার কন্ডিশন ও রেফ্রিজারেশন বিশেষজ্ঞ। ইনভার্টার এসি গ্যাস লিকেজ রিপেয়ার, ডিপ ক্লিনিং ও কম্প্রেসার মেরামত দ্রুত সম্পন্ন করি।',
    phoneNumber: '০১৮১২-৪৪৫৫৬৬',
    email: 'tarik.ac@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['এসি টেকনিশিয়ান (AC Technician)', 'রেফ্রিজারেটর মেরামত'],
    mainProfession: 'এসি টেকনিশিয়ান (AC Technician)',
    skills: [
      'AC Installation (এসি ফিটিং ও স্থানান্তর)',
      'Gas Refill (গ্যাস রিফিল ও লিক চেক)',
      'Compressor Repair (কম্প্রেসার মেরামত)',
      'AC Deep Cleaning (জেট ওয়াশ ও সার্ভিসিং)',
    ],
    experiences: [
      {
        profession: 'এসি টেকনিশিয়ান (AC Technician)',
        years: 6,
        description: 'ইনভার্টার এবং নন-ইনভার্টার স্প্লিট এসির সার্ভিসিং।',
        isMain: true,
      },
    ],
    workHistories: [
      {
        id: 'wh-t1',
        company: 'কুলিং কেয়ার সেন্টার',
        position: 'সিনিয়র এসি মেকানিক',
        startDate: '২০২০',
        endDate: 'চলমান',
        currentlyWorking: true,
        location: 'ধানমন্ডি, ঢাকা',
        jobDetails: 'বাসা ও অফিসের এসি মেইনটেন্যান্স ও ইমার্জেন্সি রিপেয়ার।',
      },
    ],
    serviceAreas: ['ধানমন্ডি', 'মোহাম্মদপুর', 'লালমাটিয়া', 'শ্যামলী', 'ফার্মগেট'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'ধানমন্ডি',
      unionWard: 'ওয়ার্ড ১৫',
      areaRoad: 'রোড ৮/এ',
      fullAddress: 'ধানমন্ডি, ঢাকা',
    },
    currentLocation: {
      latitude: 23.7461,
      longitude: 90.3742,
      accuracyMeters: 15,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'ধানমন্ডি ৮/এ, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.8,
    reviewCount: 29,
    completedJobsCount: 62,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-03-abul',
    fullName: 'আবুল কালাম',
    bio: 'দক্ষ প্লাম্বার ও পাইপফিটার। পানির লাইন লিকেজ, বাথরুম ফিটিংস, কমোড রিপ্লেসমেন্ট এবং পানির পাম্প (মোটর) মেরামত করি।',
    phoneNumber: '০১৯১১-৭৭৮৮৯৯',
    email: 'abul.plumber@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['প্লাম্বার (Plumber)', 'পানির পাম্প মেরামত'],
    mainProfession: 'প্লাম্বার (Plumber)',
    skills: [
      'Pipe Leakage Repair (পাইপ লিকেজ সমাধান)',
      'Bathroom Fittings (বাথরুম ফিটিংস)',
      'Water Pump Servicing (পানির পাম্প মেরামত)',
      'Sanitary Repair (স্যানিটারি লাইন ক্লিয়ার)',
    ],
    experiences: [
      {
        profession: 'প্লাম্বার (Plumber)',
        years: 8,
        description: 'স্যানিটারি ও স্যুয়ারেজ লাইনের টেকসই সমাধান।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['মিরপুর-১', 'মিরপুর-১০', 'কল্যাণপুর', 'গাবতলী'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      unionWard: 'ওয়ার্ড ৮',
      areaRoad: 'রোড ১, ব্লক এ',
      fullAddress: 'মিরপুর ১, ঢাকা',
    },
    currentLocation: {
      latitude: 23.7956,
      longitude: 90.3537,
      accuracyMeters: 12,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'মিরপুর ১ গোলচত্বর, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.7,
    reviewCount: 21,
    completedJobsCount: 45,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 90,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-04-belal',
    fullName: 'মো: বেলাল হোসেন',
    bio: 'পেশাদার রঙ মিস্ত্রি ও ইন্টেরিয়র পেইন্টার। আবহাওয়া প্রতিরোধী প্লাস্টিক পেইন্ট, ওয়েদার কোট ও কাঠের বার্নিশের নিখুঁত কাজ।',
    phoneNumber: '০১৬১১-৩৩৪৪৪৫',
    email: 'belal.painter@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    isOnline: false, // Offline worker example
    availabilityUpdatedAt: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['রং মিস্ত্রি (Painter)', 'কাঠের বার্নিশ'],
    mainProfession: 'রং মিস্ত্রি (Painter)',
    skills: [
      'Wall Painting (ওয়াল পেইন্টিং)',
      'Weather Coat (আবহাওয়া প্রতিরোধী রং)',
      'Wood Polish (কাঠের বার্নিশ ও পলিশ)',
      'Putty Work (ওয়াল পুটিং ফিনিশিং)',
    ],
    experiences: [
      {
        profession: 'রং মিস্ত্রি (Painter)',
        years: 12,
        description: 'বড় আবাসিক প্রজেক্ট ও ফ্ল্যাটের সম্পূর্ণ রং কাজ।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['উত্তরা (সেক্টর ১-১৪)', 'বিমানবন্দর', 'টঙ্গী'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'উত্তরা',
      unionWard: 'সেক্টর ৭',
      areaRoad: 'রোড ৩',
      fullAddress: 'সেক্টর ৭, উত্তরা, ঢাকা',
    },
    rating: 4.9,
    reviewCount: 35,
    completedJobsCount: 71,
    joinedDate: '২০২২',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-05-sumon',
    fullName: 'সুমন আহমেদ',
    bio: 'কম্পিউটার হার্ডওয়্যার, ল্যাপটপ মেরামত, সিসিটিভি ক্যামেরা ইনস্টলেশন ও হোম নেটওয়ার্কিং টেকনিশিয়ান।',
    phoneNumber: '০১৫১১-৯৯৮৮৭৭',
    email: 'sumon.it@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    isOnline: false, // Offline worker example
    availabilityUpdatedAt: new Date(Date.now() - 3600 * 1000 * 14).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600 * 1000 * 14).toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['কম্পিউটার ও ল্যাপটপ মেরামত', 'সিসিটিভি টেকনিশিয়ান'],
    mainProfession: 'কম্পিউটার ও ল্যাপটপ মেরামত',
    skills: [
      'Hardware Repair (হার্ডওয়্যার মেরামত)',
      'OS & Software Setup (উইন্ডোজ ও সফটওয়্যার সেটআপ)',
      'CCTV Camera Installation (সিসিটিভি ইনস্টল)',
      'WiFi Router Configuration (ওয়াইফাই রাউটার সেটআপ)',
    ],
    experiences: [
      {
        profession: 'কম্পিউটার ও ল্যাপটপ মেরামত',
        years: 5,
        description: 'মাদারবোর্ড রিপেয়ার ও নেটওয়ার্কিং।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['গুলশান', 'বনানী', 'মহাখালী', 'বাড্ডা'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'গুলশান',
      unionWard: 'ওয়ার্ড ১৯',
      areaRoad: 'রোড ১১',
      fullAddress: 'গুলশান ১, ঢাকা',
    },
    rating: 4.6,
    reviewCount: 18,
    completedJobsCount: 39,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 90,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-06-jahir',
    fullName: 'মো: জহিরুল ইসলাম',
    bio: 'অভিজ্ঞ কাঠমিস্ত্রি। ফার্নিচার মেরামত, নতুন আসবাব তৈরি, ডোর লক ও কব্জা ফিটিংসের কাজ দক্ষ হাতে করি।',
    phoneNumber: '০১৭২২-০০১১২২',
    email: 'jahir.carpenter@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['কাঠমিস্ত্রি (Carpenter)', 'ফার্নিচার মেরামত'],
    mainProfession: 'কাঠমিস্ত্রি (Carpenter)',
    skills: [
      'Door Lock & Hinge (দরজা ও লক ফিটিং)',
      'Furniture Repair (আসবাবপত্র মেরামত)',
      'Kitchen Cabinet (কিচেন ক্যাবিনেট তৈরি)',
      'Custom Woodwork (কাস্টম কাঠের কাজ)',
    ],
    experiences: [
      {
        profession: 'কাঠমিস্ত্রি (Carpenter)',
        years: 9,
        description: 'অফিস ও বাসার আধুনিক কাঠের আসবাবপত্র নির্মাণ।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['যাত্রাবাড়ী', 'ওয়ারী', 'মতিঝিল', 'পুরান ঢাকা'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'যাত্রাবাড়ী',
      unionWard: 'ওয়ার্ড ৪৮',
      areaRoad: 'ধলপুর মেইন রোড',
      fullAddress: 'যাত্রাবাড়ী, ঢাকা',
    },
    currentLocation: {
      latitude: 23.7104,
      longitude: 90.4349,
      accuracyMeters: 14,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'যাত্রাবাড়ী চৌরাস্তা, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.8,
    reviewCount: 22,
    completedJobsCount: 53,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
    serviceCategoryModes: ['physical'],
  },
  {
    userId: 'worker-07-tanvir',
    fullName: 'তানভীর আহমেদ',
    bio: '৫ বছরের অভিজ্ঞ প্রফেশনাল গ্রাফিক ডিজাইনার ও লোগো স্পেশালিস্ট। সোশ্যাল মিডিয়া ব্যানার, ইউটিউব থাম্বনেইল, ভেক্টর আর্ট ও ব্র্যান্ডিংয়ে পারদর্শী। দ্রুত ডেলিভারি ও আনলিমিটেড রিভিশন।',
    phoneNumber: '০১৭৩৩-৪৪৩৩৪৫',
    email: 'tanvir.designer@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    serviceCategoryModes: ['digital'],
    professions: ['গ্রাফিক ডিজাইনার (Graphic Designer)', 'লোগো ও ব্র্যান্ড আইডেন্টিটি'],
    mainProfession: 'গ্রাফিক ডিজাইনার (Graphic Designer)',
    skills: [
      'Logo Design (লোগো ডিজাইন ও ভেক্টর)',
      'Thumbnail Design (ইউটিউব থাম্বনেইল)',
      'Social Media Post & Banner (সোশ্যাল ব্যানার)',
      'Brand Identity (কালার প্যালেট ও ব্র্যান্ডিং)',
      'Photoshop & Illustrator (ফটোশপ ও ইলাস্ট্রেটর)',
    ],
    searchKeywords: [
      'Graphic Designer', 'গ্রাফিক ডিজাইনার', 'লোগো ডিজাইন', 'Logo Design',
      'লোগো তৈরি', 'ব্যানার ডিজাইন', 'Thumbnail', 'থাম্বনেইল', 'Photoshop', 'ফটোশপ'
    ],
    experiences: [
      {
        profession: 'গ্রাফিক ডিজাইনার (Graphic Designer)',
        years: 5,
        description: 'ফাইভারে লেভেল ২ সেলার এবং ৪০০+ সফল ব্র্যান্ড আইডেন্টিটি ও লোগো সম্পন্ন।',
        isMain: true,
      },
    ],
    workHistories: [
      {
        id: 'wh-tv1',
        company: 'ডিজাইনহাউজ বিডি',
        position: 'সিনিয়র গ্রাফিক ডিজাইনার',
        startDate: '২০২১',
        endDate: 'চলমান',
        currentlyWorking: true,
        location: 'রিমোট / ঢাকা',
        jobDetails: 'আন্তর্জাতিক ক্লায়েন্টদের জন্য ব্র্যান্ড লোগো ও ডিজিটাল বিজ্ঞাপনের ভিজ্যুয়াল তৈরি।',
      },
    ],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      fullAddress: 'মিরপুর, ঢাকা',
    },
    rating: 4.95,
    reviewCount: 42,
    completedJobsCount: 110,
    joinedDate: '২০২১',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 100,
    isProfileSetupComplete: true,
    pricing: {
      hourlyRate: 500,
      dailyRate: 3000,
      isNegotiable: true,
      rateDescription: 'লোগো ডিজাইন শুরু ৳১,৫০০ থেকে • ডেলিভারি ১-২ দিন'
    },
    portfolio: [
      {
        id: 'port-1',
        title: 'অরগ্যানিক ফুডস ব্র্যান্ড লোগো ও প্যাকেজিং',
        description: 'মিনিমালিস্ট ও প্রিমিয়াম ইলাস্ট্রেশন বেসড ভেক্টর লোগো।',
        imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&auto=format&fit=crop&q=80',
        profession: 'গ্রাফিক ডিজাইনার (Graphic Designer)',
      },
      {
        id: 'port-2',
        title: 'ইউটিউব টেক চ্যানেলের হাই CTR থাম্বনেইল প্যাক',
        description: 'ক্লিক-থ্রু রেট ১৫% পর্যন্ত বৃদ্ধিকারী ক্রিয়েটিভ থাম্বনেইল।',
        imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
        profession: 'গ্রাফিক ডিজাইনার (Graphic Designer)',
      },
    ],
  },
  {
    userId: 'worker-08-farhana',
    fullName: 'ফারহানা ইসলাম',
    bio: '৪ বছরের অভিজ্ঞ ফুল-স্ট্যাক ওয়েব ডেভেলপার। আধুনিক React, Next.js, ওয়ার্ডপ্রেস ও শপিফাই দিয়ে দ্রুতগতির রেসপনসিভ ওয়েবসাইট ও ই-কমার্স প্ল্যাটফর্ম তৈরি করি।',
    phoneNumber: '০১৮৩৩-৫৫৬৬৭৭',
    email: 'farhana.dev@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    serviceCategoryModes: ['digital'],
    professions: ['ওয়েব ডেভেলপার (Web Developer)', 'ফ্রন্টএন্ড ইঞ্জিনিয়ার'],
    mainProfession: 'ওয়েব ডেভেলপার (Web Developer)',
    skills: [
      'React & Next.js (ওয়েবসাইট ডেভেলপমেন্ট)',
      'Landing Page (বিজনেস ল্যান্ডিং পেজ)',
      'E-commerce Website (অনলাইন শপ তৈরি)',
      'Tailwind CSS & Mobile Friendly (রেসপনসিভ ডিজাইন)',
      'WordPress & Shopify Setup (ওয়ার্ডপ্রেস/শপিফাই)',
    ],
    searchKeywords: [
      'Web Developer', 'ওয়েব ডেভেলপার', 'ওয়েবসাইট তৈরি', 'Website',
      'React', 'Next.js', 'Frontend', 'প্রোগ্রামার', 'ই-কমার্স ওয়েবসাইট', 'ওয়ার্ডপ্রেস'
    ],
    experiences: [
      {
        profession: 'ওয়েব ডেভেলপার (Web Developer)',
        years: 4,
        description: '৫০+ ক্লায়েন্টের জন্য বিজনেস ওয়েবসাইট ও কাস্টম ওয়েব অ্যাপ্লিকেশন ডেভেলপমেন্ট।',
        isMain: true,
      },
    ],
    workHistories: [
      {
        id: 'wh-f1',
        company: 'কোডস্পিয়ার সফটওয়্যার',
        position: 'সিনিয়র ওয়েব ডেভেলপার',
        startDate: '২০২২',
        endDate: 'চলমান',
        currentlyWorking: true,
        location: 'রিমোট',
        jobDetails: 'ই-কমার্স ও স্টার্টআপদের জন্য উচ্চগতির ল্যান্ডিং পেজ ও ওয়েব প্ল্যাটফর্ম তৈরি।',
      },
    ],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'ধানমন্ডি',
      fullAddress: 'ধানমন্ডি, ঢাকা',
    },
    rating: 4.9,
    reviewCount: 33,
    completedJobsCount: 52,
    joinedDate: '২০২২',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 100,
    isProfileSetupComplete: true,
    pricing: {
      hourlyRate: 800,
      dailyRate: 5000,
      isNegotiable: true,
      rateDescription: 'ফুল ল্যান্ডিং পেজ শুরু ৳৪,৫০০ থেকে • ডেলিভারি ২-৩ দিন'
    },
    portfolio: [
      {
        id: 'port-f1',
        title: 'ফ্যাশন ব্র্যান্ডের মডার্ন ই-কমার্স স্টোর',
        description: 'Next.js ও বিকাশ গেটওয়ে ইন্টিগ্রেশনসহ পূর্ণাঙ্গ ডিজিটাল শপ।',
        imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&auto=format&fit=crop&q=80',
        profession: 'ওয়েব ডেভেলপার (Web Developer)',
      },
    ],
  },
  {
    userId: 'worker-09-shohan',
    fullName: 'সোহানুর রহমান',
    bio: 'ইউটিউব ভিডিও, ইনস্টাগ্রাম রিলস ও টিকটক শর্টস এডিটিং এক্সপার্ট। কালার গ্রেডিং, সাউন্ড ডিজাইন ও আকর্ষণীয় মোশন ক্যাপশন যুক্ত করে কনটেন্টের ভিউজ ও রিচ বাড়িয়ে তুলি।',
    phoneNumber: '০১৬৭৭-৮৮৯৯০০',
    email: 'shohan.editor@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isOnline: false,
    availabilityUpdatedAt: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    serviceCategoryModes: ['digital'],
    professions: ['ভিডিও এডিটর (Video Editor)', 'রিলস ও শর্টস ক্রিয়েটর'],
    mainProfession: 'ভিডিও এডিটর (Video Editor)',
    skills: [
      'YouTube Video Editing (ইউটিউব ভিডিও এডিটিং)',
      'Reels & Shorts (রিলস ও শর্টস এডিটিং)',
      'Color Grading & Audio Fix (কালার ও সাউন্ড)',
      'Motion Graphics & Subtitles (সাবটাইটেল ও মোশন)',
      'Premiere Pro & After Effects',
    ],
    searchKeywords: [
      'Video Editor', 'ভিডিও এডিটর', 'ভিডিও এডিটিং', 'Video Editing',
      'রিলস', 'Reels', 'Shorts', 'শর্টস', 'ইউটিউব ভিডিও', 'Premiere Pro'
    ],
    experiences: [
      {
        profession: 'ভিডিও এডিটর (Video Editor)',
        years: 3,
        description: 'শীর্ষস্থানীয় ইউটিউবার ও ব্র্যান্ডের জন্য ২০০+ সফল ভিডিও ও রিলস সম্পাদনা।',
        isMain: true,
      },
    ],
    workHistories: [],
    presentAddress: {
      division: 'চট্টগ্রাম',
      district: 'চট্টগ্রাম',
      upazila: 'পাঁচলাইশ',
      fullAddress: 'চট্টগ্রাম',
    },
    rating: 4.85,
    reviewCount: 29,
    completedJobsCount: 78,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
    pricing: {
      hourlyRate: 600,
      isNegotiable: true,
      rateDescription: 'রিলস/শর্টস শুরু ৳৮০০ প্রতি ভিডিও • ডেলিভারি ২৪ ঘণ্টা'
    },
    portfolio: [
      {
        id: 'port-s1',
        title: 'পডকাস্ট ও টেক টক শো ভিডিও সিরিজ',
        description: 'মাল্টি-ক্যামেরা এডিটিং, অডিও নয়েজ রিমুভাল ও ডায়নামিক ক্যাপশন।',
        imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400&auto=format&fit=crop&q=80',
        profession: 'ভিডিও এডিটর (Video Editor)',
      },
    ],
  },
  {
    userId: 'worker-10-nusrat',
    fullName: 'নুসরাত জাহান',
    bio: 'সার্টিফাইড ডিজিটাল মার্কেটিং ও এসইও এক্সপার্ট। ফেসবুক ও ইনস্টাগ্রাম অ্যাড ক্যাম্পেইন, গুগল সার্চ অ্যাডস, এবং স্থানীয় ব্যবসার জন্য সেলস ফানেল তৈরির মাধ্যমে কাঙ্ক্ষিত বিক্রয় বৃদ্ধি করি।',
    phoneNumber: '০১৫২২-৩৩৪৪৫৫',
    email: 'nusrat.marketing@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    serviceCategoryModes: ['digital'],
    professions: ['ডিজিটাল মার্কেটার (Digital Marketer)', 'সোশ্যাল মিডিয়া স্পেশালিস্ট'],
    mainProfession: 'ডিজিটাল মার্কেটার (Digital Marketer)',
    skills: [
      'Facebook & Insta Ads (ফেসবুক বিজ্ঞাপন ক্যাম্পেইন)',
      'Google Search Ads (গুগল অ্যাডস ও পিপিসি)',
      'SEO Optimization (সার্চ ইঞ্জিন র‍্যাংকিং)',
      'Social Media Page Management (পেজ ম্যানেজমেন্ট)',
      'ROAS Optimization (সেলস ফানেল ও রিটার্ন)',
    ],
    searchKeywords: [
      'Digital Marketer', 'ডিজিটাল মার্কেটার', 'ডিজিটাল মার্কেটিং', 'Marketing',
      'Facebook Ads', 'ফেসবুক বুস্ট', 'SEO', 'এসইও', 'মার্কেটিং'
    ],
    experiences: [
      {
        profession: 'ডিজিটাল মার্কেটার (Digital Marketer)',
        years: 4,
        description: '৬০+ লোকাল ই-কমার্স ও বুটিক শপের ডিজিটাল মার্কেটিং ও সেলস গ্রোথ নিশ্চিতকরণ।',
        isMain: true,
      },
    ],
    workHistories: [],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'গুলশান',
      fullAddress: 'গুলশান, ঢাকা',
    },
    rating: 4.88,
    reviewCount: 25,
    completedJobsCount: 44,
    joinedDate: '২০২২',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
    pricing: {
      isNegotiable: true,
      rateDescription: 'ক্যাম্পেইন সেটআপ শুরু ৳২,০০০ থেকে • মান্থলি প্যাকেজ উপলব্ধ'
    },
  },
];

export const SAMPLE_SEED_HIRE_REQUESTS: HireRequest[] = [
  {
    id: 'HL-HR-10021',
    customerId: 'user-demo-01',
    customerName: 'মো: রফিকুল ইসলাম',
    customerPhone: '০১৭০০-১২৩৪৫৬',
    workerId: 'worker-01-shafiq',
    workerName: 'মো: শফিকুল ইসলাম',
    workerPhone: '০১৭০১-১২২৩৩৩',
    workerAvatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'ইলেকট্রিশিয়ান (Electrician)',
    workType: 'সিলিং ফ্যান ফিটিং ও মেইন সুইচ রিপেয়ার',
    description: 'ড্রয়িং রুমের সিলিং ফ্যান খুলে নতুন রেগুলেটর লাগাতে হবে এবং ডিস্ট্রিবিউশন বক্সের একটি সার্কিট ব্রেকার স্পার্ক করছে। জরুরি সমাধান প্রয়োজন।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      areaRoad: 'রোড ৪, ব্লক বি',
      fullAddress: 'বাড়ি ১২, রোড ৪, ব্লক বি, মিরপুর-১০, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-১০',
    preferredTime: 'বিকাল ০৪:০০',
    budget: 800,
    status: 'QUOTED',
    quote: {
      estimatedPrice: 750,
      quoteNote: 'ফ্যান ফিটিং ও সার্কিট ব্রেকার চেঞ্জ করতে আনুমানিক ১ থেকে ১.৫ ঘণ্টা সময় লাগবে। পার্টসের খরচ আলাদা হবে।',
      quotedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    },
    conversationId: 'conv-hl-hr-10021',
    createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    quotedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
  {
    id: 'HL-HR-10022',
    customerId: 'user-customer-sakib',
    customerName: 'সাকিব আল হাসান',
    customerPhone: '০১৭৮৮-৯৯০০১১',
    workerId: 'worker-02-tarik',
    workerName: 'তারেক মাহমুদ',
    workerPhone: '০১৮১২-৪৪৫৫৬৬',
    workerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'এসি টেকনিশিয়ান (AC Technician)',
    workType: '১.৫ টন ইনভার্টার এসি গ্যাস রিফিল ও জেট ওয়াশ',
    description: 'বেডরুমের জেনারেল ১.৫ টন এসি ঠান্ডা হচ্ছে না, ইনডোর ইউনিটে পানি পড়ছে। জেট ওয়াশ করে গ্যাস চেক করাতে হবে।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'ধানমন্ডি',
      areaRoad: 'রোড ২৭',
      fullAddress: 'ফ্ল্যাট ৪বি, বাড়ি ৫৮, রোড ২৭, ধানমন্ডি, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-১১',
    preferredTime: 'সকাল ১১:০০',
    budget: 2500,
    agreedPrice: 2400,
    serviceFeeBreakdown: {
      feeEnabled: true,
      agreedPrice: 2400,
      commissionPercentage: 5,
      fixedFee: 10,
      calculatedFee: 130,
      workerReceivable: 2270,
      customerPayable: 2400,
      calculatedAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
    },
    status: 'ACCEPTED',
    conversationId: 'conv-hl-hr-10022',
    createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    quotedAt: new Date(Date.now() - 3600 * 1000 * 20).toISOString(),
    acceptedAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
  },
  {
    id: 'HL-HR-10023',
    customerId: 'user-demo-01',
    customerName: 'মো: রফিকুল ইসলাম',
    customerPhone: '০১৭০০-১২৩৪৫৬',
    workerId: 'worker-03-abul',
    workerName: 'আবুল কালাম',
    workerPhone: '০১৯১১-৭৭৮৮৯৯',
    workerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'প্লাম্বার (Plumber)',
    workType: 'বাথরুম পাইপ লিকেজ ও পানির মোটর চেক',
    description: 'ছাদের ওভারহেড ট্যাংকের ইনলেট পাইপ ফেটে পানি পড়ছে। নিচতলার পাম্পের প্রেশারও কমে গেছে। জরুরি মেরামত চাই।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      areaRoad: 'রোড ৪',
      fullAddress: 'বাড়ি ১২, রোড ৪, ব্লক বি, মিরপুর-১০, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-০৯',
    preferredTime: 'দুপুর ০২:০০',
    budget: 1200,
    agreedPrice: 1100,
    serviceFeeBreakdown: {
      feeEnabled: true,
      agreedPrice: 1100,
      commissionPercentage: 5,
      fixedFee: 10,
      calculatedFee: 65,
      workerReceivable: 1035,
      customerPayable: 1100,
      calculatedAt: new Date(Date.now() - 3600 * 1000 * 44).toISOString(),
    },
    status: 'WORK_COMPLETED',
    conversationId: 'conv-hl-hr-10023',
    createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    quotedAt: new Date(Date.now() - 3600 * 1000 * 46).toISOString(),
    acceptedAt: new Date(Date.now() - 3600 * 1000 * 44).toISOString(),
    startedAt: new Date(Date.now() - 3600 * 1000 * 42).toISOString(),
    completedAt: new Date(Date.now() - 3600 * 1000 * 40).toISOString(),
    ratingSubmitted: true,
    ratingValue: 5,
    ratingComment: 'খুবই দ্রুত এসেছেন এবং অত্যন্ত দক্ষতার সাথে পাইপ বদলে দিয়েছেন। ব্যবহারে অমায়িক।',
  },
  {
    id: 'HL-HR-10024',
    customerId: 'user-demo-01',
    customerName: 'মো: রফিকুল ইসলাম',
    customerPhone: '০১৭০০-১২৩৪৫৬',
    workerId: 'worker-06-jahir',
    workerName: 'মো: জহিরুল ইসলাম',
    workerPhone: '০১৭২২-০০১১২২',
    workerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'কাঠমিস্ত্রি (Carpenter)',
    workType: 'মেইন ডোর লক ও কিচেন ক্যাবিনেট কব্জা মেরামত',
    description: 'মেইন দরজার ডিজিটাল লক জ্যাম হয়ে আছে এবং রান্নাঘরের ২ টি ক্যাবিনেট পাল্লা হেলে পড়েছে।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      areaRoad: 'রোড ৪',
      fullAddress: 'বাড়ি ১২, রোড ৪, ব্লক বি, মিরপুর-১০, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-১২',
    preferredTime: 'সকাল ১০:৩০',
    budget: 600,
    status: 'REQUESTED',
    conversationId: 'conv-hl-hr-10024',
    createdAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
  },
];

export const SAMPLE_SEED_REVIEWS: ServiceReview[] = [
  {
    id: 'rev-01',
    hireRequestId: 'HL-HR-10023',
    reviewerId: 'user-demo-01',
    reviewerName: 'মো: রফিকুল ইসলাম',
    revieweeId: 'worker-03-abul',
    rating: 5,
    comment: 'খুবই দ্রুত এসেছেন এবং অত্যন্ত দক্ষতার সাথে পাইপ বদলে দিয়েছেন। ব্যবহারে অমায়িক ও সময়নিষ্ঠ।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 40).toISOString(),
  },
  {
    id: 'rev-02',
    hireRequestId: 'HL-HR-9988',
    reviewerId: 'user-tanzim-01',
    reviewerName: 'তানজিম হোসেন',
    revieweeId: 'worker-01-shafiq',
    rating: 5,
    comment: 'শফিকুল ভাই একজন সত্যিকারের দক্ষ কারিগর। পুরো বাসার ওয়্যারিং নিখুঁতভাবে চেক করে দিয়েছেন।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 120).toISOString(),
  },
  {
    id: 'rev-03',
    hireRequestId: 'HL-HR-9985',
    reviewerId: 'user-nasreen-02',
    reviewerName: 'নাসরীন জাহান',
    revieweeId: 'worker-02-tarik',
    rating: 5,
    comment: 'এসি জেট ওয়াশ করার পর বরফের মতো ঠান্ডা হচ্ছে। কোনো বাড়তি টাকা চাননি, যা কথা তাই নিয়েছেন।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 150).toISOString(),
  },
  {
    id: 'rev-04',
    hireRequestId: 'HL-HR-9980',
    reviewerId: 'user-fahim-03',
    reviewerName: 'ফাহিম মোর্শেদ',
    revieweeId: 'worker-01-shafiq',
    rating: 4.8,
    comment: 'সার্কিট ব্রেকার সমস্যা দ্রুত সমাধান করেছেন। কাজ শেষে পরিষ্কার-পরিচ্ছন্ন করে গেছেন।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 200).toISOString(),
  },
];
