import { UserProfile, HireRequest, ServiceReview, HireAdminSettings } from '../types';

export const DEFAULT_HIRE_ADMIN_SETTINGS: HireAdminSettings = {
  minServiceBudget: 200,
  maxServiceBudget: 50000,
  defaultSearchRadiusKm: 15,
  requireVerificationForWork: true,
  requestExpirationHours: 24,
  cancellationWindowHours: 2,
  // Automated Service Fee / Commission Settings (Step 4)
  serviceFeeEnabled: true,
  commissionPercentage: 5,
  fixedServiceFee: 10,
  minServiceFee: 10,
  maxServiceFee: 500,
  feeEffectiveDate: '2026-01-01',
};

export const SAMPLE_SEED_WORKERS: UserProfile[] = [
  {
    userId: 'worker-01-shafiq',
    fullName: 'মো: শফিকুল ইসলাম',
    bio: '১০ বছরের অভিজ্ঞ মাস্টার ইলেকট্রিশিয়ান ও সার্কিট ডিজাইনার। যেকোনো ধরনের জটিল ওয়্যারিং, ফ্যান, লাইট, সার্কিট ব্রেকার ও সাব-স্টেশন সংযোগে দক্ষ।',
    phoneNumber: '০১৭০১-১২২৩৩৩',
    email: 'shafiq.tech@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker', 'customer'],
    capabilities: ['worker', 'customer'],
    professions: ['ইলেকট্রিশিয়ান (Electrician)', 'আইপিএস ও সোলার টেকনিশিয়ান'],
    mainProfession: 'ইলেকট্রিশিয়ান (Electrician)',
    skills: [
      'Fan Installation (ফ্যান ফিটিং)',
      'House Wiring (হাউস ওয়্যারিং)',
      'MCB Installation (সার্কিট ব্রেকার)',
      'Switch Repair (সুইচবোর্ড মেরামত)',
      'Generator Servicing (জেনারেটর সার্ভিসিং)',
    ],
    experiences: [
      {
        profession: 'ইলেকট্রিশিয়ান (Electrician)',
        years: 10,
        description: 'আবাসিক ও বাণিজ্যিক কমপ্লেক্সের পূর্ণাঙ্গ ইলেকট্রিক ওয়্যারিং সমাধান।',
        isMain: true,
      },
    ],
    workHistories: [
      {
        id: 'wh-s1',
        company: 'পাওয়ারটেক বিডি লিমিটেড',
        position: 'চিফ ইলেকট্রিশিয়ান',
        startDate: '২০১৮',
        endDate: 'চলমান',
        currentlyWorking: true,
        location: 'মিরপুর, ঢাকা',
        jobDetails: 'অ্যাপার্টমেন্ট প্রজেক্ট ও কমার্শিয়াল ভবনে বিদ্যুৎ সংযোগ স্থাপন।',
      },
    ],
    serviceAreas: ['মিরপুর-১০', 'মিরপুর-২', 'পল্লবী', 'কাজীপাড়া', 'শেওড়াপাড়া', 'উত্তরা'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      unionWard: 'ওয়ার্ড ৩',
      areaRoad: 'রোড ২, ব্লক সি',
      fullAddress: 'মিরপুর ১০, ঢাকা',
    },
    currentLocation: {
      latitude: 23.8071,
      longitude: 90.3686,
      accuracyMeters: 10,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'মিরপুর ১০ গোলচত্বর, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.9,
    reviewCount: 38,
    completedJobsCount: 84,
    joinedDate: '২০২২',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 100,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-02-tarik',
    fullName: 'তারেক মাহমুদ',
    bio: 'সার্টিফাইড এয়ার কন্ডিশন ও রেফ্রিজারেশন বিশেষজ্ঞ। ইনভার্টার এসি গ্যাস লিকেজ রিপেয়ার, ডিপ ক্লিনিং ও কম্প্রেসার মেরামত দ্রুত সম্পন্ন করি।',
    phoneNumber: '০১৮১২-৪৪৫৫৬৬',
    email: 'tarik.ac@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['এসি টেকনিশিয়ান (AC Technician)', 'রেফ্রিজারেটর মেরামত'],
    mainProfession: 'এসি টেকনিশিয়ান (AC Technician)',
    skills: [
      'AC Installation (এসি ফিটিং ও স্থানান্তর)',
      'Gas Refill (গ্যাস রিফিল ও লিক চেক)',
      'Compressor Repair (কম্প্রেসার মেরামত)',
      'AC Deep Cleaning (জেট ওয়াশ ও সার্ভিসিং)',
    ],
    experiences: [
      {
        profession: 'এসি টেকনিশিয়ান (AC Technician)',
        years: 6,
        description: 'ইনভার্টার এবং নন-ইনভার্টার স্প্লিট এসির সার্ভিসিং।',
        isMain: true,
      },
    ],
    workHistories: [
      {
        id: 'wh-t1',
        company: 'কুলিং কেয়ার সেন্টার',
        position: 'সিনিয়র এসি মেকানিক',
        startDate: '২০২০',
        endDate: 'চলমান',
        currentlyWorking: true,
        location: 'ধানমন্ডি, ঢাকা',
        jobDetails: 'বাসা ও অফিসের এসি মেইনটেন্যান্স ও ইমার্জেন্সি রিপেয়ার।',
      },
    ],
    serviceAreas: ['ধানমন্ডি', 'মোহাম্মদপুর', 'লালমাটিয়া', 'শ্যামলী', 'ফার্মগেট'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'ধানমন্ডি',
      unionWard: 'ওয়ার্ড ১৫',
      areaRoad: 'রোড ৮/এ',
      fullAddress: 'ধানমন্ডি, ঢাকা',
    },
    currentLocation: {
      latitude: 23.7461,
      longitude: 90.3742,
      accuracyMeters: 15,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'ধানমন্ডি ৮/এ, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.8,
    reviewCount: 29,
    completedJobsCount: 62,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-03-abul',
    fullName: 'আবুল কালাম',
    bio: 'দক্ষ প্লাম্বার ও পাইপফিটার। পানির লাইন লিকেজ, বাথরুম ফিটিংস, কমোড রিপ্লেসমেন্ট এবং পানির পাম্প (মোটর) মেরামত করি।',
    phoneNumber: '০১৯১১-৭৭৮৮৯৯',
    email: 'abul.plumber@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['প্লাম্বার (Plumber)', 'পানির পাম্প মেরামত'],
    mainProfession: 'প্লাম্বার (Plumber)',
    skills: [
      'Pipe Leakage Repair (পাইপ লিকেজ সমাধান)',
      'Bathroom Fittings (বাথরুম ফিটিংস)',
      'Water Pump Servicing (পানির পাম্প মেরামত)',
      'Sanitary Repair (স্যানিটারি লাইন ক্লিয়ার)',
    ],
    experiences: [
      {
        profession: 'প্লাম্বার (Plumber)',
        years: 8,
        description: 'স্যানিটারি ও স্যুয়ারেজ লাইনের টেকসই সমাধান।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['মিরপুর-১', 'মিরপুর-১০', 'কল্যাণপুর', 'গাবতলী'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      unionWard: 'ওয়ার্ড ৮',
      areaRoad: 'রোড ১, ব্লক এ',
      fullAddress: 'মিরপুর ১, ঢাকা',
    },
    currentLocation: {
      latitude: 23.7956,
      longitude: 90.3537,
      accuracyMeters: 12,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'মিরপুর ১ গোলচত্বর, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.7,
    reviewCount: 21,
    completedJobsCount: 45,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 90,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-04-belal',
    fullName: 'মো: বেলাল হোসেন',
    bio: 'পেশাদার রঙ মিস্ত্রি ও ইন্টেরিয়র পেইন্টার। আবহাওয়া প্রতিরোধী প্লাস্টিক পেইন্ট, ওয়েদার কোট ও কাঠের বার্নিশের নিখুঁত কাজ।',
    phoneNumber: '০১৬১১-৩৩৪৪৪৫',
    email: 'belal.painter@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    isOnline: false, // Offline worker example
    availabilityUpdatedAt: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['রং মিস্ত্রি (Painter)', 'কাঠের বার্নিশ'],
    mainProfession: 'রং মিস্ত্রি (Painter)',
    skills: [
      'Wall Painting (ওয়াল পেইন্টিং)',
      'Weather Coat (আবহাওয়া প্রতিরোধী রং)',
      'Wood Polish (কাঠের বার্নিশ ও পলিশ)',
      'Putty Work (ওয়াল পুটিং ফিনিশিং)',
    ],
    experiences: [
      {
        profession: 'রং মিস্ত্রি (Painter)',
        years: 12,
        description: 'বড় আবাসিক প্রজেক্ট ও ফ্ল্যাটের সম্পূর্ণ রং কাজ।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['উত্তরা (সেক্টর ১-১৪)', 'বিমানবন্দর', 'টঙ্গী'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'উত্তরা',
      unionWard: 'সেক্টর ৭',
      areaRoad: 'রোড ৩',
      fullAddress: 'সেক্টর ৭, উত্তরা, ঢাকা',
    },
    rating: 4.9,
    reviewCount: 35,
    completedJobsCount: 71,
    joinedDate: '২০২২',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-05-sumon',
    fullName: 'সুমন আহমেদ',
    bio: 'কম্পিউটার হার্ডওয়্যার, ল্যাপটপ মেরামত, সিসিটিভি ক্যামেরা ইনস্টলেশন ও হোম নেটওয়ার্কিং টেকনিশিয়ান।',
    phoneNumber: '০১৫১১-৯৯৮৮৭৭',
    email: 'sumon.it@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    isOnline: false, // Offline worker example
    availabilityUpdatedAt: new Date(Date.now() - 3600 * 1000 * 14).toISOString(),
    lastActiveAt: new Date(Date.now() - 3600 * 1000 * 14).toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['কম্পিউটার ও ল্যাপটপ মেরামত', 'সিসিটিভি টেকনিশিয়ান'],
    mainProfession: 'কম্পিউটার ও ল্যাপটপ মেরামত',
    skills: [
      'Hardware Repair (হার্ডওয়্যার মেরামত)',
      'OS & Software Setup (উইন্ডোজ ও সফটওয়্যার সেটআপ)',
      'CCTV Camera Installation (সিসিটিভি ইনস্টল)',
      'WiFi Router Configuration (ওয়াইফাই রাউটার সেটআপ)',
    ],
    experiences: [
      {
        profession: 'কম্পিউটার ও ল্যাপটপ মেরামত',
        years: 5,
        description: 'মাদারবোর্ড রিপেয়ার ও নেটওয়ার্কিং।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['গুলশান', 'বনানী', 'মহাখালী', 'বাড্ডা'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'গুলশান',
      unionWard: 'ওয়ার্ড ১৯',
      areaRoad: 'রোড ১১',
      fullAddress: 'গুলশান ১, ঢাকা',
    },
    rating: 4.6,
    reviewCount: 18,
    completedJobsCount: 39,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 90,
    isProfileSetupComplete: true,
  },
  {
    userId: 'worker-06-jahir',
    fullName: 'মো: জহিরুল ইসলাম',
    bio: 'অভিজ্ঞ কাঠমিস্ত্রি। ফার্নিচার মেরামত, নতুন আসবাব তৈরি, ডোর লক ও কব্জা ফিটিংসের কাজ দক্ষ হাতে করি।',
    phoneNumber: '০১৭২২-০০১১২২',
    email: 'jahir.carpenter@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    isOnline: true,
    availabilityUpdatedAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    verificationStatus: 'verified',
    roles: ['worker'],
    capabilities: ['worker'],
    professions: ['কাঠমিস্ত্রি (Carpenter)', 'ফার্নিচার মেরামত'],
    mainProfession: 'কাঠমিস্ত্রি (Carpenter)',
    skills: [
      'Door Lock & Hinge (দরজা ও লক ফিটিং)',
      'Furniture Repair (আসবাবপত্র মেরামত)',
      'Kitchen Cabinet (কিচেন ক্যাবিনেট তৈরি)',
      'Custom Woodwork (কাস্টম কাঠের কাজ)',
    ],
    experiences: [
      {
        profession: 'কাঠমিস্ত্রি (Carpenter)',
        years: 9,
        description: 'অফিস ও বাসার আধুনিক কাঠের আসবাবপত্র নির্মাণ।',
        isMain: true,
      },
    ],
    workHistories: [],
    serviceAreas: ['যাত্রাবাড়ী', 'ওয়ারী', 'মতিঝিল', 'পুরান ঢাকা'],
    presentAddress: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'যাত্রাবাড়ী',
      unionWard: 'ওয়ার্ড ৪৮',
      areaRoad: 'ধলপুর মেইন রোড',
      fullAddress: 'যাত্রাবাড়ী, ঢাকা',
    },
    currentLocation: {
      latitude: 23.7104,
      longitude: 90.4349,
      accuracyMeters: 14,
      lastUpdated: new Date().toISOString(),
      formattedAddress: 'যাত্রাবাড়ী চৌরাস্তা, ঢাকা',
      sharePermissionGranted: true,
    },
    rating: 4.8,
    reviewCount: 22,
    completedJobsCount: 53,
    joinedDate: '২০২৩',
    subscriptionPlan: 'free',
    subscriptionActive: true,
    profileCompletedPercentage: 95,
    isProfileSetupComplete: true,
  },
];

export const SAMPLE_SEED_HIRE_REQUESTS: HireRequest[] = [
  {
    id: 'HL-HR-10021',
    customerId: 'user-demo-01',
    customerName: 'মো: রফিকুল ইসলাম',
    customerPhone: '০১৭০০-১২৩৪৫৬',
    workerId: 'worker-01-shafiq',
    workerName: 'মো: শফিকুল ইসলাম',
    workerPhone: '০১৭০১-১২২৩৩৩',
    workerAvatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'ইলেকট্রিশিয়ান (Electrician)',
    workType: 'সিলিং ফ্যান ফিটিং ও মেইন সুইচ রিপেয়ার',
    description: 'ড্রয়িং রুমের সিলিং ফ্যান খুলে নতুন রেগুলেটর লাগাতে হবে এবং ডিস্ট্রিবিউশন বক্সের একটি সার্কিট ব্রেকার স্পার্ক করছে। জরুরি সমাধান প্রয়োজন।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      areaRoad: 'রোড ৪, ব্লক বি',
      fullAddress: 'বাড়ি ১২, রোড ৪, ব্লক বি, মিরপুর-১০, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-১০',
    preferredTime: 'বিকাল ০৪:০০',
    budget: 800,
    status: 'QUOTED',
    quote: {
      estimatedPrice: 750,
      quoteNote: 'ফ্যান ফিটিং ও সার্কিট ব্রেকার চেঞ্জ করতে আনুমানিক ১ থেকে ১.৫ ঘণ্টা সময় লাগবে। পার্টসের খরচ আলাদা হবে।',
      quotedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    },
    conversationId: 'conv-hl-hr-10021',
    createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    quotedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
  {
    id: 'HL-HR-10022',
    customerId: 'user-customer-sakib',
    customerName: 'সাকিব আল হাসান',
    customerPhone: '০১৭৮৮-৯৯০০১১',
    workerId: 'worker-02-tarik',
    workerName: 'তারেক মাহমুদ',
    workerPhone: '০১৮১২-৪৪৫৫৬৬',
    workerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'এসি টেকনিশিয়ান (AC Technician)',
    workType: '১.৫ টন ইনভার্টার এসি গ্যাস রিফিল ও জেট ওয়াশ',
    description: 'বেডরুমের জেনারেল ১.৫ টন এসি ঠান্ডা হচ্ছে না, ইনডোর ইউনিটে পানি পড়ছে। জেট ওয়াশ করে গ্যাস চেক করাতে হবে।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'ধানমন্ডি',
      areaRoad: 'রোড ২৭',
      fullAddress: 'ফ্ল্যাট ৪বি, বাড়ি ৫৮, রোড ২৭, ধানমন্ডি, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-১১',
    preferredTime: 'সকাল ১১:০০',
    budget: 2500,
    agreedPrice: 2400,
    serviceFeeBreakdown: {
      feeEnabled: true,
      agreedPrice: 2400,
      commissionPercentage: 5,
      fixedFee: 10,
      calculatedFee: 130,
      workerReceivable: 2270,
      customerPayable: 2400,
      calculatedAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
    },
    status: 'ACCEPTED',
    conversationId: 'conv-hl-hr-10022',
    createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    quotedAt: new Date(Date.now() - 3600 * 1000 * 20).toISOString(),
    acceptedAt: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
  },
  {
    id: 'HL-HR-10023',
    customerId: 'user-demo-01',
    customerName: 'মো: রফিকুল ইসলাম',
    customerPhone: '০১৭০০-১২৩৪৫৬',
    workerId: 'worker-03-abul',
    workerName: 'আবুল কালাম',
    workerPhone: '০১৯১১-৭৭৮৮৯৯',
    workerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'প্লাম্বার (Plumber)',
    workType: 'বাথরুম পাইপ লিকেজ ও পানির মোটর চেক',
    description: 'ছাদের ওভারহেড ট্যাংকের ইনলেট পাইপ ফেটে পানি পড়ছে। নিচতলার পাম্পের প্রেশারও কমে গেছে। জরুরি মেরামত চাই।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      areaRoad: 'রোড ৪',
      fullAddress: 'বাড়ি ১২, রোড ৪, ব্লক বি, মিরপুর-১০, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-০৯',
    preferredTime: 'দুপুর ০২:০০',
    budget: 1200,
    agreedPrice: 1100,
    serviceFeeBreakdown: {
      feeEnabled: true,
      agreedPrice: 1100,
      commissionPercentage: 5,
      fixedFee: 10,
      calculatedFee: 65,
      workerReceivable: 1035,
      customerPayable: 1100,
      calculatedAt: new Date(Date.now() - 3600 * 1000 * 44).toISOString(),
    },
    status: 'WORK_COMPLETED',
    conversationId: 'conv-hl-hr-10023',
    createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    quotedAt: new Date(Date.now() - 3600 * 1000 * 46).toISOString(),
    acceptedAt: new Date(Date.now() - 3600 * 1000 * 44).toISOString(),
    startedAt: new Date(Date.now() - 3600 * 1000 * 42).toISOString(),
    completedAt: new Date(Date.now() - 3600 * 1000 * 40).toISOString(),
    ratingSubmitted: true,
    ratingValue: 5,
    ratingComment: 'খুবই দ্রুত এসেছেন এবং অত্যন্ত দক্ষতার সাথে পাইপ বদলে দিয়েছেন। ব্যবহারে অমায়িক।',
  },
  {
    id: 'HL-HR-10024',
    customerId: 'user-demo-01',
    customerName: 'মো: রফিকুল ইসলাম',
    customerPhone: '০১৭০০-১২৩৪৫৬',
    workerId: 'worker-06-jahir',
    workerName: 'মো: জহিরুল ইসলাম',
    workerPhone: '০১৭২২-০০১১২২',
    workerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    workerProfession: 'কাঠমিস্ত্রি (Carpenter)',
    workType: 'মেইন ডোর লক ও কিচেন ক্যাবিনেট কব্জা মেরামত',
    description: 'মেইন দরজার ডিজিটাল লক জ্যাম হয়ে আছে এবং রান্নাঘরের ২ টি ক্যাবিনেট পাল্লা হেলে পড়েছে।',
    workLocation: {
      division: 'ঢাকা',
      district: 'ঢাকা',
      upazila: 'মিরপুর (১০ নং সেক্টর)',
      areaRoad: 'রোড ৪',
      fullAddress: 'বাড়ি ১২, রোড ৪, ব্লক বি, মিরপুর-১০, ঢাকা',
    },
    preferredDate: '২০২৬-০৩-১২',
    preferredTime: 'সকাল ১০:৩০',
    budget: 600,
    status: 'REQUESTED',
    conversationId: 'conv-hl-hr-10024',
    createdAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
  },
];

export const SAMPLE_SEED_REVIEWS: ServiceReview[] = [
  {
    id: 'rev-01',
    hireRequestId: 'HL-HR-10023',
    reviewerId: 'user-demo-01',
    reviewerName: 'মো: রফিকুল ইসলাম',
    revieweeId: 'worker-03-abul',
    rating: 5,
    comment: 'খুবই দ্রুত এসেছেন এবং অত্যন্ত দক্ষতার সাথে পাইপ বদলে দিয়েছেন। ব্যবহারে অমায়িক ও সময়নিষ্ঠ।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 40).toISOString(),
  },
  {
    id: 'rev-02',
    hireRequestId: 'HL-HR-9988',
    reviewerId: 'user-tanzim-01',
    reviewerName: 'তানজিম হোসেন',
    revieweeId: 'worker-01-shafiq',
    rating: 5,
    comment: 'শফিকুল ভাই একজন সত্যিকারের দক্ষ কারিগর। পুরো বাসার ওয়্যারিং নিখুঁতভাবে চেক করে দিয়েছেন।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 120).toISOString(),
  },
  {
    id: 'rev-03',
    hireRequestId: 'HL-HR-9985',
    reviewerId: 'user-nasreen-02',
    reviewerName: 'নাসরীন জাহান',
    revieweeId: 'worker-02-tarik',
    rating: 5,
    comment: 'এসি জেট ওয়াশ করার পর বরফের মতো ঠান্ডা হচ্ছে। কোনো বাড়তি টাকা চাননি, যা কথা তাই নিয়েছেন।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 150).toISOString(),
  },
  {
    id: 'rev-04',
    hireRequestId: 'HL-HR-9980',
    reviewerId: 'user-fahim-03',
    reviewerName: 'ফাহিম মোর্শেদ',
    revieweeId: 'worker-01-shafiq',
    rating: 4.8,
    comment: 'সার্কিট ব্রেকার সমস্যা দ্রুত সমাধান করেছেন। কাজ শেষে পরিষ্কার-পরিচ্ছন্ন করে গেছেন।',
    createdAt: new Date(Date.now() - 3600 * 1000 * 200).toISOString(),
  },
];
